<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Seeder para tabla categoría
         */

        $categorias = [
            ['id' => 1, 'nombre' => 'RESOLUCIONES', 'seccion_id' => 1],
            ['id' => 26, 'nombre' => 'DECRETOS', 'seccion_id' => 2],
            ['id' => 27, 'nombre' => 'LEYES', 'seccion_id' => 3],
            ['id' => 28, 'nombre' => 'ANEXOS', 'seccion_id' => 4],
            ['id' => 29, 'nombre' => 'Anexos - Resolucion 5544 Dic.172003 [ 17122003]', 'seccion_id' => 4],
            ['id' => 31, 'nombre' => 'SISTEMA DE CONTROL INTERNO', 'seccion_id' => 5],
            ['id' => 32, 'nombre' => 'GESTIÓN ADMINISTRATIVA', 'seccion_id' => 5],
            ['id' => 33, 'nombre' => 'TALENTO HUMANO', 'seccion_id' => 5],
        ];

        DB::table('categorias')->insert($categorias);


        $categorias = [
            ['id' => 2, 'nombre' => 'AÑO 2000', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 3, 'nombre' => 'AÑO 2002', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 4, 'nombre' => 'AÑO 2003', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 5, 'nombre' => 'AÑO 2004', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 6, 'nombre' => 'AÑO 2005', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 7, 'nombre' => 'AÑO 2006', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 8, 'nombre' => 'AÑO 2007', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 9, 'nombre' => 'AÑO 2008', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 10, 'nombre' => 'AÑO 2009', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 11, 'nombre' => 'AÑO 2010', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 12, 'nombre' => 'AÑO 2011', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 13, 'nombre' => 'AÑO 2012', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 14, 'nombre' => 'AÑO 2013', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 15, 'nombre' => 'AÑO 2014', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 16, 'nombre' => 'AÑO 2015', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 17, 'nombre' => 'AÑO 2016', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 18, 'nombre' => 'AÑO 2017', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 19, 'nombre' => 'AÑO 2018', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 20, 'nombre' => 'AÑO 2019', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 21, 'nombre' => 'AÑO 2020', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 22, 'nombre' => 'AÑO 2021', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 23, 'nombre' => 'AÑO 2022', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 24, 'nombre' => 'AÑO 2023', 'seccion_id' => 1, 'categoria_id' => 1],
            ['id' => 25, 'nombre' => 'EXTERNAS', 'seccion_id' => 1, 'categoria_id' => 22],
            ['id' => 30, 'nombre' => '2022', 'seccion_id' => 4, 'categoria_id' => 28],
            ['id' => 34, 'nombre' => '01 INFORMES OFICINA CONTROL INTERNO', 'seccion_id' => 5, 'categoria_id' => 31],
            ['id' => 35, 'nombre' => '02 COMPONENTES DEL SISTEMA DE CONTROL INTERNO', 'seccion_id' => 5, 'categoria_id' => 31],
            ['id' => 65, 'nombre' => 'GASTOS SERVICIOS PUBLICOS', 'seccion_id' => 5, 'categoria_id' => 32],
            ['id' => 66, 'nombre' => 'SERVICIOS PUBLICOS', 'seccion_id' => 5, 'categoria_id' => 32],
            ['id' => 76, 'nombre' => 'CAPACITACIONES Y BIENESTAR', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 77, 'nombre' => 'CLIMA LABORAL', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 78, 'nombre' => 'CODIGO DE INTEGRIDAD', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 79, 'nombre' => 'COMISION PERSONAL', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 80, 'nombre' => 'COOPASST FPS', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 81, 'nombre' => 'ENTORNO LABORAL Y TRABAJO SALUDABLE', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 82, 'nombre' => 'EVALUACIÓN DE DESEMPEÑO', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 83, 'nombre' => 'FACTORES DE RIESGOS PSICOSOCIALES', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 84, 'nombre' => 'MANUALES DE FUNCIONES', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 85, 'nombre' => 'MATRIZ DE PELIGROS EVALUACION Y VALORACION DE RIESGOS', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 86, 'nombre' => 'NOTICIAS', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 87, 'nombre' => 'NOVEDADES / VACACIONES', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 88, 'nombre' => 'POLITICAS DE SST', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 89, 'nombre' => 'SEGURIDAD Y SALUD EN EL TRABAJO', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 90, 'nombre' => 'TELETRABAJO', 'seccion_id' => 5, 'categoria_id' => 33],
            ['id' => 36, 'nombre' => 'DERECHOS DE AUTOR', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 37, 'nombre' => 'EVALUACION DEL SISTEMA DE CONTROL INTERNO CONTABLE', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 38, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO A PLANES DE MEJORAMIENTO', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 39, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO A PLANES DE MEJORAMIENTO SUPER SALUD', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 40, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO AL PLAN DE AUSTERIDAD DEL GASTO', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 41, 'nombre' => 'INFORME AUDITORÍA DE SEGUIMIENTO AL PLAN DE MEJORAMIENTO ARCHIVÍSTICO', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 42, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO AL PLAN ESTRATÉGICO SECTORIAL E INSTITUCIONAL', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 43, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO AL PRODUCTO Y/O SERVICIO NO CONFORME', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 44, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO DE MIPG', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 45, 'nombre' => 'INFORME AUDITORIA DE SEGUIMIENTO RENDICIÓN DE CUENTAS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 46, 'nombre' => 'INFORME FORMULARIO UNICO DE REPORTE Y AVANCE DE GESTION – FURAG.', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 47, 'nombre' => 'INFORME PLAN ANUAL DE AUDITORIA BASADO EN RIESGOS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 48, 'nombre' => 'INFORME SEMESTRAL DE EVALUACION INDEPENDIENTE DEL ESTADO DEL SISTEMA DE CONTROL INTERNO', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 49, 'nombre' => 'INFORMES AUDITORIA DE SEGUIMIENTO A LA MATRIZ PLAN DE ACCION', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 50, 'nombre' => 'INFORMES AUDITORIA DE SEGUIMIENTO A LA RED INTERINSTITUCIONAL DE TRANSPARENCIA Y ANTICORRUPCION RITA', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 51, 'nombre' => 'INFORMES AUDITORÍA DE SEGUIMIENTO AL PLAN MANEJO DE RIESGOS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 52, 'nombre' => 'INFORMES AUDITORIA DE SEGUIMIENTO EVALUACION AL SIGEP', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 53, 'nombre' => 'INFORMES AUDITORIA DE SEGUIMIENTO MATRIZ AGREGADA DE INDICADORES ESTRATEGICOS Y POR PROCESOS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 54, 'nombre' => 'INFORMES AUDITORIA DE SEGUIMIENTO SECOP II', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 55, 'nombre' => 'INFORMES AUDITORIA DE SEGUIMIENTO Y REVISION AL SIG - (SG-SST) , SEGURIDAD INFORMACION, AMBIENTAL Y MIPG)', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 56, 'nombre' => 'INFORMES AUDITORIA GIT PRESTACIONES SERVICIOS DE SALUD', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 57, 'nombre' => 'INFORMES AUDITORIAS INTERNAS A PROCESOS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 58, 'nombre' => 'INFORMES DE AUDITORÍA A LAS PQRS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 59, 'nombre' => 'INFORMES DE SEGUIMIENTO COMITES INSTITUCIONALES', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 60, 'nombre' => 'INFORMES EKOGUI', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 61, 'nombre' => 'INFORMES EVALUACION DE GESTION POR DEPENDENCIAS', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 62, 'nombre' => 'INFORMES SIRECI', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 63, 'nombre' => 'INFORMES SUIT - RACIONALIZACIÓN DE TRÁMITES', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 64, 'nombre' => 'RESULTADOS EVALUACIÓN SISTEMA DE CONTROL INTERNO', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 190, 'nombre' => 'SEGUIMIENTO AL SISTEMA DE ALERTAS DE CONTROL INTERNO (SACI)', 'seccion_id' => 5, 'categoria_id' => 34],
            ['id' => 192, 'nombre' => 'ADOPCION Y PLANEACION DEL MECI', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 193, 'nombre' => 'AUTOCONTROL', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 194, 'nombre' => 'EVALUACION INDEPENDIENTE', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 195, 'nombre' => 'MECI - CALIDAD', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 196, 'nombre' => 'MEDICAS (PAMEC)', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 197, 'nombre' => 'NUEVO MODELO ESTANDAR DE CONTROL INTERNO', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 198, 'nombre' => 'POLITICAS ADMINISTRACION DEL RIESGO', 'seccion_id' => 5, 'categoria_id' => 35],
            ['id' => 91, 'nombre' => '2016', 'seccion_id' => 5, 'categoria_id' => 36],
            ['id' => 92, 'nombre' => '2017', 'seccion_id' => 5, 'categoria_id' => 36],
            ['id' => 93, 'nombre' => '2020', 'seccion_id' => 5, 'categoria_id' => 36],
            ['id' => 94, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 36],
            ['id' => 95, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 36],
            ['id' => 96, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 36],
            ['id' => 97, 'nombre' => '2019', 'seccion_id' => 5, 'categoria_id' => 37],
            ['id' => 98, 'nombre' => '2020', 'seccion_id' => 5, 'categoria_id' => 37],
            ['id' => 99, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 37],
            ['id' => 100, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 37],
            ['id' => 101, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 37],
            ['id' => 102, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 38],
            ['id' => 103, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 38],
            ['id' => 104, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 38],
            ['id' => 105, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 38],
            ['id' => 106, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 40],
            ['id' => 107, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 40],
            ['id' => 108, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 40],
            ['id' => 109, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 40],
            ['id' => 110, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 41],
            ['id' => 111, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 41],
            ['id' => 112, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 41],
            ['id' => 113, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 42],
            ['id' => 114, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 42],
            ['id' => 115, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 42],
            ['id' => 116, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 43],
            ['id' => 117, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 43],
            ['id' => 118, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 43],
            ['id' => 119, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 44],
            ['id' => 120, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 44],
            ['id' => 121, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 44],
            ['id' => 122, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 44],
            ['id' => 123, 'nombre' => '2020', 'seccion_id' => 5, 'categoria_id' => 45],
            ['id' => 124, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 45],
            ['id' => 125, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 45],
            ['id' => 126, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 46],
            ['id' => 127, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 46],
            ['id' => 128, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 47],
            ['id' => 129, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 47],
            ['id' => 130, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 47],
            ['id' => 131, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 48],
            ['id' => 132, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 48],
            ['id' => 133, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 48],
            ['id' => 134, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 48],
            ['id' => 135, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 49],
            ['id' => 136, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 49],
            ['id' => 137, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 49],
            ['id' => 138, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 49],
            ['id' => 139, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 50],
            ['id' => 140, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 50],
            ['id' => 141, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 50],
            ['id' => 142, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 51],
            ['id' => 143, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 51],
            ['id' => 144, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 51],
            ['id' => 145, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 51],
            ['id' => 146, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 52],
            ['id' => 147, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 52],
            ['id' => 148, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 52],
            ['id' => 149, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 52],
            ['id' => 150, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 53],
            ['id' => 151, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 53],
            ['id' => 152, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 53],
            ['id' => 153, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 54],
            ['id' => 154, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 54],
            ['id' => 155, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 54],
            ['id' => 156, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 54],
            ['id' => 157, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 55],
            ['id' => 158, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 55],
            ['id' => 159, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 55],
            ['id' => 160, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 56],
            ['id' => 161, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 57],
            ['id' => 162, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 57],
            ['id' => 163, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 57],
            ['id' => 164, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 57],
            ['id' => 165, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 58],
            ['id' => 166, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 58],
            ['id' => 167, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 58],
            ['id' => 168, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 58],
            ['id' => 169, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 59],
            ['id' => 170, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 59],
            ['id' => 171, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 59],
            ['id' => 172, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 60],
            ['id' => 173, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 60],
            ['id' => 174, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 60],
            ['id' => 175, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 60],
            ['id' => 176, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 61],
            ['id' => 177, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 61],
            ['id' => 178, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 61],
            ['id' => 179, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 62],
            ['id' => 180, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 62],
            ['id' => 181, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 62],
            ['id' => 182, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 63],
            ['id' => 183, 'nombre' => '2022', 'seccion_id' => 5, 'categoria_id' => 63],
            ['id' => 184, 'nombre' => '2023', 'seccion_id' => 5, 'categoria_id' => 63],
            ['id' => 185, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 63],
            ['id' => 186, 'nombre' => '2006', 'seccion_id' => 5, 'categoria_id' => 64],
            ['id' => 187, 'nombre' => '2019', 'seccion_id' => 5, 'categoria_id' => 64],
            ['id' => 188, 'nombre' => '2020', 'seccion_id' => 5, 'categoria_id' => 64],
            ['id' => 189, 'nombre' => '2021', 'seccion_id' => 5, 'categoria_id' => 64],
            ['id' => 67, 'nombre' => '2012', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 68, 'nombre' => '2013', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 69, 'nombre' => '2014', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 70, 'nombre' => '2015', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 71, 'nombre' => '2016', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 72, 'nombre' => '2017', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 73, 'nombre' => '2018', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 74, 'nombre' => '2019', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 75, 'nombre' => '2020', 'seccion_id' => 5, 'categoria_id' => 65],
            ['id' => 206, 'nombre' => 'EQUIPOS EXCELENCIA METODOLOGICA', 'seccion_id' => 5, 'categoria_id' => 76],
            ['id' => 207, 'nombre' => 'GESTION DOCUMENTAL FPS', 'seccion_id' => 5, 'categoria_id' => 76],
            ['id' => 208, 'nombre' => 'PLANES DE CAPACITACIÓN Y BIENESTAR', 'seccion_id' => 5, 'categoria_id' => 76],
            ['id' => 209, 'nombre' => 'PRESENTACIONES - CAPACITACIONES FPS', 'seccion_id' => 5, 'categoria_id' => 76],
            ['id' => 210, 'nombre' => 'SEMINARIOS GOBIERNO EN LINEA', 'seccion_id' => 5, 'categoria_id' => 76],
            ['id' => 211, 'nombre' => 'PLANES DE SEGURIDAD Y SALUD EN EL TRABAJO 2016', 'seccion_id' => 5, 'categoria_id' => 89],
            ['id' => 212, 'nombre' => 'PLANES DE SEGURIDAD Y SALUD EN EL TRABAJO 2017', 'seccion_id' => 5, 'categoria_id' => 89],
            ['id' => 213, 'nombre' => 'PLANES DE SEGURIDAD Y SALUD EN EL TRABAJO 2018', 'seccion_id' => 5, 'categoria_id' => 89],
            ['id' => 214, 'nombre' => 'PLANES DE SEGURIDAD Y SALUD EN EL TRABAJO 2019', 'seccion_id' => 5, 'categoria_id' => 89],
            ['id' => 215, 'nombre' => 'PLANES DE SEGURIDAD Y SALUD EN EL TRABAJO 2020', 'seccion_id' => 5, 'categoria_id' => 89],
            ['id' => 191, 'nombre' => '2024', 'seccion_id' => 5, 'categoria_id' => 190],
            ['id' => 199, 'nombre' => '2019', 'seccion_id' => 5, 'categoria_id' => 194],
            ['id' => 200, 'nombre' => '2014', 'seccion_id' => 5, 'categoria_id' => 195],
            ['id' => 201, 'nombre' => '2015', 'seccion_id' => 5, 'categoria_id' => 195],
            ['id' => 202, 'nombre' => '2016', 'seccion_id' => 5, 'categoria_id' => 195],
            ['id' => 203, 'nombre' => '2017', 'seccion_id' => 5, 'categoria_id' => 195],
            ['id' => 204, 'nombre' => 'DOCUMENTOS DE CAMILO', 'seccion_id' => 5, 'categoria_id' => 198],
            ['id' => 205, 'nombre' => 'MANUALES', 'seccion_id' => 5, 'categoria_id' => 198],
            ['id' => 216, 'nombre' => 'PAE002 2015 CODIGO VALORES', 'seccion_id' => 5, 'categoria_id' => 206],
            ['id' => 217, 'nombre' => 'PAE002 2015 LEY ESTATUTARIA', 'seccion_id' => 5, 'categoria_id' => 206],
            ['id' => 218, 'nombre' => 'CAPACITACIONES POLITICA SINAPSIS 2019', 'seccion_id' => 5, 'categoria_id' => 209],
            ['id' => 219, 'nombre' => 'CAPACITACIONES POLITICA SINAPSIS 2020', 'seccion_id' => 5, 'categoria_id' => 209],
            ['id' => 220, 'nombre' => 'CAPACITACIONES POLITICA SINAPSIS 2021', 'seccion_id' => 5, 'categoria_id' => 209],
            ['id' => 221, 'nombre' => 'CAPACITACIONES POLITICA SINAPSIS 2022', 'seccion_id' => 5, 'categoria_id' => 209],
            ['id' => 222, 'nombre' => 'CAPACITACIONES POLITICA SINAPSIS 2023', 'seccion_id' => 5, 'categoria_id' => 209],
            ['id' => 223, 'nombre' => 'DOCUMENTOS AGN', 'seccion_id' => 5, 'categoria_id' => 209],
            ['id' => 224, 'nombre' => 'REINDUCCION 2016', 'seccion_id' => 5, 'categoria_id' => 209],
        ];

        DB::table('categorias')->insert($categorias);
    }
}
