<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaginaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Seeder para tabla paginas
         */

        $paginas = [
            ['nombre' => 'INFORMACIÓN GENERAL', 'contenido' => '<p>El Fondo de Pasivo Social de Ferrocarriles Nacionales de Colombia, es un establecimiento público vinculado al Ministerio de Trabajo y Seguridad Social que fue creado por el Estado para asumir las consecuencias laborales de un siglo de operación ferroviaria Nacional.</p><p>Tal vez, la normalidad de su accionar en procura del cumplimiento de sus objetivos principalísimos, no lo haya colocado en lugar de protagonismo que no concordaría con sus condiciones de discreción, desempeño austero y silencioso, donde sólo importa el cumplimiento de su misión, llenando de satisfacción a los destinatarios de sus servicios, que inicialmente fueron los exempleados de esa gran empresa estatal que marcó el desarrollo del país, pero además ha cumplido con Colombia, porque ha sabido administrar los recursos públicos con honestidad y transparencia, ganándose la confianza de varios gobiernos que le han entregado nuevas obligaciones y no precisamente, de aquellas sencillas, si no de las que requieren delicada labor.</p><p>Así fue como asumió la administración de los servicios asistenciales que se prestan a los pensionados de la empresa Puertos de Colombia y sus familias, que hoy puede presentarse como ejemplo de pulcritud, calidad, responsabilidad y disciplina de los usuarios.</p><p>Adicionalmente, el Fondo ha desarrollado mecanismos de control para los programas de Ferrocarriles Nacionales y Puertos de Colombia, que involucran directamente a los usuarios del servicio, desarrollando un verdadero programa de participación ciudadana, pues nuestros afiliados integran los Comités de Veeduría en cada punto de atención y además hacen parte de los Comités de Evaluación locales, regionales y nacionales, siendo esta entidad la única en el país que de esta manera tiene permanente control y evaluación por parte de los pensionados, que han permitido los magníficos resultados que se conocen.</p>', 'estado' => 1],
            ['nombre' => 'INSTITUCIONALIDAD', 'contenido' => '<h3><strong>Misión</strong></h3><p>El Fondo de Pasivo Social de Ferrocarriles Nacionales de Colombia&nbsp; como establecimiento público del orden Nacional, adaptado en salud&nbsp; y adscrito al Ministerio de Salud y Protección Social,&nbsp; reconoce, organiza y administra prestaciones económicas legales y convencionales y los servicios de salud a los extrabajadores, pensionados y beneficiarios de las liquidadas empresas Ferrocarriles Nacionales de Colombia y Puertos de Colombia respectivamente, brindando servicios integrales con calidad, oportunidad y transparencia, en cumplimiento de la normatividad legal vigente.</p><h3><strong>Visión</strong></h3><p>El Fondo de Pasivo Social de Ferrocarriles Nacionales de Colombia, será reconocido en el 2033, por el estado colombiano por haber logrado la acreditación en la atención integral en salud a los afiliados, contribuyendo con la sostenibilidad del Sistema de Seguridad Social y Gestor de Pasivos de la Nación brindando un servicio con mayor calidad, oportunidad y eficiencia contribuyendo con las políticas de gestión pública, para el cumplimiento de los fines esenciales del Estado.</p>', 'estado' => 1],
            ['nombre' => 'ORGANIGRAMA', 'contenido' => '<figure class="image"><img style="aspect-ratio:1260/660;" src="https://intranet.fps.gov.co/aym_image/images/Organigrama%20(1).jpg" width="1260" height="660"></figure>', 'estado' => 1],
            ['nombre' => 'POLÍTICA DEL SISTEMA INTEGRADO DE GESTIÓN', 'contenido' => '<p style="text-align:justify;">El Fondo de Pasivo Social de los Ferrocarriles Nacionales de Colombia (FPS-FNC) decidacado a reconocer prestaciones económicas legales y convencionales a los extrabajadores, pensionado y beneficiarios de los extintos Ferrocarriles Nacionales de Colombia; así como a administrar los servicios de salud a los pensionados de los extintos Ferrocarriles Nacionales de Colombia y Puertos de Colombia.</p><p style="text-align:justify;">Se compromete a:</p><p style="text-align:justify;">&nbsp;</p><ul><li>Gestionar todos los riesgos y oportunidades del Sistema Integrado de Gestión (SIG-MIPG). Controlando y eliminando los peligros identificados y reduciendo los riesgos de la Seguridad y Salud en el Trabajo, generando medidas de intervención para el beneficio de todos los colaboradores de la entidad.</li><li>Proteger el medio ambiente y prevenir la contaminación identificando, controlando, y/o eliminando los impactos ambientales negativos generados en el desempeño de nuestras actividades por consumo de recursos naturales y generación de residuos.</li><li>Conservar y asegurar el bienestar y promoción de la salud a todos sus colaboradores a través de la implementación del Subsistema de Gestión de la Seguridad y Salud en el Trabajo en el desarrollo de actividades de promoción y prevención de lesiones y el deterioro de la salud, con el fin de minimizar las enfermedades laborales y evitar los accidentes de trabajo, promoviendo la consulta y participación de los trabajadores.</li><li>Proteger, conservar y asegurar los activos de información basados en una metodología de riesgos con el objeto de minimizar el nivel de exposición frente a amenzas internas o externas, que permita responder por la integridad, confidencialidad y la disponibilidad de la misma.</li><li>Diseñar e implementar los mecanismos y herramientas para la gestión de los documentos internos y externos necesarios para el cumplimiento de la misión y visión institucional, con el fin de garantizar la integridad, autenticidad, veracidad y seguridad del manejo de toda la información institucional dirigida a la implementación de los instrumentos archivísticos y puestos a disposición de la ciudadanía, funcionarios y contratistas del FPS-FNC.</li><li>Cumpliendo los requisitos de nuestros grupos de valor, legales y técnicos aplicables de la entidad, en el marco de la mejora continua de los procesos a través de la implementación de herramientas de gestión.</li></ul><p><a href="https://intranet.fps.gov.co/aym_image/files/Dise%C3%B1o%20PDF%20Pol%C3%ACtica%20del%20SIG_compressed(1).pdf">POLÍTICA SIG</a></p><p>&nbsp;</p><figure class="image"><img style="aspect-ratio:1280/720;" src="https://intranet.fps.gov.co/aym_image/images/MAPA%20DE%20PROCESOS(1).jpg" width="1280" height="720"></figure>', 'estado' => 1],
            ['nombre' => 'OBJETIVOS ESTRATÉGICOS', 'contenido' => '<ul><li>Garantizar la efectiva organización y administración de los servicios de salud para asegurar una prestación óptima a nuestros usuarios, a través de asistencias técnicas a los prestadores de servicios de salud, y del seguimiento a los indicadores de resultado seleccionados en las rutas de atención integral en salud (RIAS) y los grupos de riesgo priorizados desde la vigencia 2024 hasta la vigencia 2026.</li><li>Garantizar la administración, reconocimiento y pago eficiente de prestaciones económicas mediante una gestión oportuna y ordenada, a través de la atención del 100% de las solicitudes de reconocimientos que cumplen los requisitos establecidos en la normatividad, y de la implementación de los trámites en línea.</li><li>Fortalecer y mantener el SIG -FPS en el marco del MIPG, para mejorar los resultados de Medición del Desempeño Institucional a 95 puntos; a través del cumplimiento de las políticas de desarrollo administrativo.</li><li>Fortalecer y modernizar los sistemas de información del FPS FNC, para asegurar\r\n la operación efectiva y una retroalimentación constante con sus usuarios y ciudadanos desde la vigencia 2023 hasta la vigencia 2026.</li><li>Fortalecer la administración de los bienes de la entidad y la óptima gestión de los recursos financieros durante el cuatrienio 2023-2026.</li><li>Fomentar la mejora de la calidad de los servicios de salud ofrecidos por el FPS FNC, a través de la implementación del Programa de auditoría para el\r\n mejoramiento de la calidad PAMEC.</li><li>Reducir los impactos ambientales significativos derivados de los aspectos ambientales de la operación del FPS FNC, mediante prácticas sostenibles, garantizando el cumplimiento de la normativa vigente para los periodos 2024 y 2026, mediante la gestión de residuos, consumo de agua y energía.</li><li>Reducir la tasa de incidentes y accidentes laborales mediante la implementación efectiva del Subsistema de Gestión de la Seguridad y Salud en el Trabajo, promoviendo la prevención de lesiones y enfermedades laborales, y fomentando la participación activa de los trabajadores del FPS FNC.</li></ul>', 'estado' => 1],
            ['nombre' => 'FUNCIONES', 'contenido' => '<ul><li>Pagar las pensiones legales y convencionales de los ex empleados de la empresa Ferrocarriles Nacionales de Colombia;</li><li>Atender las demás prestaciones económicas y asistenciales de las personas a que se refiere el literal anterior;</li><li>Efectuar el reconocimiento y pago de las pensiones de cualquier naturaleza de los empleados que adquieran ese derecho en la empresa Ferrocarriles Nacionales de Colombia en Liquidación;</li><li>Efectuar el reconocimiento y pago de las demás prestaciones sociales de los empleados de la empresa Ferrocarriles Nacionales de Colombia en Liquidación;</li><li>Cancelar al organismo de previsión social o a la entidad o empresa empleadora que haya hecho el pago de pensiones a empleados que hayan laborado en la empresa Ferrocarriles Nacionales de Colombia, la cuota parte que le corresponda por el tiempo servido en esta entidad y, repetir contra terceros las cuotas partes pensionales a favor de la empresa Ferrocarriles Nacionales de Colombia o del Fondo mismo;</li><li>Efectuar el pago de las indemnizaciones que se establezcan en ejercicio de las facultades a que se refiere la Ley 21 de 1988.</li><li>Efectuar el pago de las sumas reconocidas por sentencias condenatorias laborales ejecutoriadas o que se ejecutorien a cargo de la empresa Ferrocarriles Nacionales de Colombia;</li><li>Reconocer y pagar las demás prestaciones y beneficios que le correspondan o se establezcan en ejercicio de las facultades a que se refiere la Ley 21 de 1988;</li><li>Expedir con la aprobación del Gobierno Nacional, reglamentos generales para la atención de las prestaciones y demás obligaciones a su cargo.</li><li>Realizar inversiones que garanticen seguridad, rentabilidad y liquidez a su patrimonio, con el fin de que pueda cumplir oportunamente sus obligaciones;</li><li>Ejercitar o impugnar las acciones judiciales y administrativas necesarias para la defensa y protección de los intereses de la Nación, de la empresa Ferrocarriles Nacionales de Colombia y del Fondo mismo, derivadas del cumplimiento de lo dispuesto en el artículo 7º de la Ley 21 de 1988 o de las que se generen como consecuencia del desarrollo de las facultades de que trata la citada ley;</li><li>Administrar los bienes del Fondo. Para dicho efecto podrá entre otras funciones, adquirir, enajenar, arrendar y gravar tanto los muebles como los inmuebles;</li><li>Las demás que se deriven de la ley o de sus estatutos.</li></ul>', 'estado' => 1],
            ['nombre' => 'RESOLUCIONES', 'contenido' => '', 'estado' => 1],
            ['nombre' => 'DECRETOS', 'contenido' => '', 'estado' => 1],
            ['nombre' => 'LEYES', 'contenido' => '', 'estado' => 1],
            ['nombre' => 'ANEXOS', 'contenido' => '', 'estado' => 1],
            ['nombre' => 'RECURSOS', 'contenido' => '', 'estado' => 1],
            ['nombre' => 'SISTEMA INTEGRADO DE GESTIÓN', 'contenido' => '', 'estado' => 1],
            ['nombre' => 'DIRECTORIO TELEFÓNICO', 'contenido' => '', 'estado' => 1],
        ];

        DB::table('paginas')->insert($paginas);
    }
}
