<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Seeder para tabla Usuarios
         */

        $users = [
            ['name' => 'Yeison Briceño', 'email' => 'yeison@mail.com', 'password' => Hash::make('123'), 'rol_id' => 1],
            ['name' => 'Angelica Campo Araujo', 'email' => 'angelica.campo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Abigail Martinez Gonzalez', 'email' => 'abigail.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alberto Gutierrez', 'email' => 'alberto.gutierrez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alejandra Calixto Medrano', 'email' => 'alejandra.calixto@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alejandra Sanchez Gonzalez', 'email' => 'alejandra.sanchez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alejandra Santos', 'email' => 'alejandra.santos@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alexander Rodriguez Castañeda', 'email' => 'alexander.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alfredo Jose Nadjar Romero', 'email' => 'alfredo.nadjar@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alfredo Jose Florez Otero', 'email' => 'alfredo.florez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alvaro Jose Dangond Sierra', 'email' => 'alvaro.dangond@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Alvaro Mauricio Buelvas Jayk', 'email' => 'alvaro.buelvas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Carolina Feris Cordoba', 'email' => 'ana.feris@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'ANA FRANCISCA QUINTERO GARCIA', 'email' => 'ana.quintero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Maria Rodriguez De Arce', 'email' => 'ana.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Maria Zarrate', 'email' => 'ana.zarrate@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Milena Ruiz Lopez', 'email' => 'ana.ruiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Milena Barandica Gonzalez', 'email' => 'ana.barandica@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Paola Anaya Garcia', 'email' => 'ana.anaya@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ana Yoselin Baquero Perez', 'email' => 'ana.baquero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andrea Manosalva Martínez', 'email' => 'andrea.manosalva@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andrea del Pilar Pisco Salazar', 'email' => 'andrea.pisco@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andrea Lucia Daza Dangond', 'email' => 'andrea.daza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andrea Stella Ñustes Pinzon', 'email' => 'andrea.nustes@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andres David Garcia Perez', 'email' => 'andresd.garcia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andres David Pimienta Ojeda', 'email' => 'andres.pimienta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andres Felipe Gongora Sanchez', 'email' => 'andres.gongora@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andres Felipe Trujillo Galvis', 'email' => 'andres.trujillo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andres Gerardo Castro Garcia', 'email' => 'andres.castro@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andres Sebastian Merlano Corena', 'email' => 'andres.merlano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Andrés Felipe Esquivel Bautista', 'email' => 'andres.esquivel@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angel Robert Torres Florez', 'email' => 'robert.torres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angela Cespedes Sanabria', 'email' => 'angela.cespedes@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angela Viviana Perez Moreno', 'email' => 'angela.perez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Anghie Carolina Moya Brugés', 'email' => 'anghie.moya@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angie Carolina Naranjo Duran', 'email' => 'angie.naranjo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angie Paola Abello Niño', 'email' => 'angie.abello@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angie Tatiana Rayo Parra', 'email' => 'angie.rayo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Angélica Maria Sanchez Alvarez', 'email' => 'angelica.sanchez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Anuar Mercado Bustamante', 'email' => 'anuar.mercado@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Arturo Arrieta', 'email' => 'arturo.arrieta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Arturo Alvira Gutierrez', 'email' => 'arturo.alvira@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Aura Estefania Guarin Armenta', 'email' => 'aura.guarin@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Beatriz Leiva Bohorquez', 'email' => 'beatriz.leiva@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Beatriz Elena Rendon Barragan', 'email' => 'beatriz.rendon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Bella Allison Celedon Avila', 'email' => 'bella.celedon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Blanca Samaris Matallana Sotelo', 'email' => 'blanca.matallana@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Camilo Nader Nader', 'email' => 'camilo.nader@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Camilo Abelardo Aguilar Duran', 'email' => 'camilo.aguilar@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Camilo Alberto Ronderos Corredor', 'email' => 'camilo.ronderos@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Camilo Andres Luque Gomez', 'email' => 'camilo.luque@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Camilo Jose Rodriguez', 'email' => 'camilo.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Quiñones', 'email' => 'carlos.quinones@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Alberto Martinez Cruz', 'email' => 'carlos.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Alberto Caicedo Cobo', 'email' => 'carlos.caicedo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Alonso Reyes Rodriguez', 'email' => 'carlos.reyes@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Andres Rojas Tirado', 'email' => 'carlos.rojas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Andres Lopez Quintero', 'email' => 'carlos.lopez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Andres Montoya Baena', 'email' => 'carlos.montoya@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Andres Granados Guevara', 'email' => 'carlos.granados@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Andrés Rodriguez Alvarado', 'email' => 'carlos.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Arturo Saucedo Alvarado', 'email' => 'carlos.saucedo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos David Gonzalez amell', 'email' => 'carlos.gonzalez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Eduardo Habib Olivella', 'email' => 'carlos.habib@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Eduardo León Guerrero', 'email' => 'carlos.leon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Julio Ramos Ramirez', 'email' => 'carlos.ramos@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Mario Quintero López', 'email' => 'carlos.quintero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carlos Omar Vega', 'email' => 'carlos.vega@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carmen Yaneth Visbal Viloria', 'email' => 'carmen.visbal@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carolina Gonzalez Rodriguez', 'email' => 'carolina.gonzalez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Carolina Andrea Escobar', 'email' => 'carolina.escobar@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Catherine Dueñas Piraban', 'email' => 'catherine.duenas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Catherine Ivette Navas', 'email' => 'catherine.navas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Cecilia Estella Forero Arevalo', 'email' => 'cecilia.forero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Cecilia Maria Pinto Perez', 'email' => 'cecilia.pinto@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ciro Andrés Campo Cruz', 'email' => 'ciro.campo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ciro Jorge Edgar Sanchez Castro', 'email' => 'ciro.sanchez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Clara Cecilia Rodriguez Pachon', 'email' => 'clara.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Clara Ines Dueñas Beltran', 'email' => 'clara.duenas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Claudia Ximena Perez Aguilar', 'email' => 'claudia.perez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Cristian Jiménez Cruz', 'email' => 'cristian.jimenez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Cristian Camilo Rodriguez Hoyos', 'email' => 'cristian.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Dahyana Melissa Hernandez Heredia', 'email' => 'dahyana.hernandez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Daniel Diaz', 'email' => 'daniel.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Daniela Ayazo Rendon', 'email' => 'daniela.ayazo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Danilo Ivan Lopez Sanabria', 'email' => 'danilo.lopez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Darly Zulay Rosero Enriquez', 'email' => 'darly.rosero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Darwin Max Giraldo Acero', 'email' => 'darwin.giraldo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Darío José Caicedo Peralta', 'email' => 'dario.caicedo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'David Alonso Marin', 'email' => 'david.marin@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'David Andres Jimenez Castro', 'email' => 'david.jimenez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'David Santiago Zuluaga', 'email' => 'david.zuluaga@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Dayana Perez Buelvas', 'email' => 'dayana.perez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Denysse Johana Ortiz Duarte', 'email' => 'denysse.ortiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Diana Serna', 'email' => 'diana.serna@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Diana Carolina Torres Diaz', 'email' => 'diana.torres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Diana Lucia Pineda Tellez', 'email' => 'diana.pineda@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Diana Valentina Serrato Gutierrez', 'email' => 'diana.serrato@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Diego Fernando Niño', 'email' => 'diego.nino@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Dora Liliana Corzo Güiza', 'email' => 'dora.corzo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Eddy Lorena Torres Chitiva', 'email' => 'eddy.torres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Edison Efraín Benitez Ortiz', 'email' => 'edison.benitez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Edith Esther Molina', 'email' => 'edith.molina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Eduardo Arenas Betancourt', 'email' => 'eduardo.arenas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Eduin Fernando Pachon Medina', 'email' => 'eduin.pachon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Edward Aldrin Robles Guerra', 'email' => 'edward.robles@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Edy Karine Olivares Olivella', 'email' => 'edy.olivares@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Elbert Navarro Hernandez', 'email' => 'elbert.navarro@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Eliana Andrea Ospina Ocampo', 'email' => 'eliana.ospina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Elieht Vanessa Quintero Barbosa', 'email' => 'elieht.quintero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Elisa Carolina Rodriguez Torres', 'email' => 'elisa.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Elkin Saul Torres Diaz', 'email' => 'elkin.torres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Elvis Castro Herrera', 'email' => 'elvis.castro@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Emely Alexandra Meneses Prieto', 'email' => 'emely.meneses@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Emerson Meneses Gonzalez', 'email' => 'emerson.meneses@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Erika Ximena Arias Fisco', 'email' => 'erika.arias@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ernesto Lozano Diaz', 'email' => 'ernesto.lozano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ernesto Elias Mendez Ruiz', 'email' => 'ernesto.mendez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Esteban Alberto Restrepo Pava', 'email' => 'esteban.restrepo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Eudiana Gonzalez Maestre', 'email' => 'eudiana.gonzalez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Fabián Jesús Suarez Beltrán', 'email' => 'fabian.suarez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Fanny Stella Medina Aleman', 'email' => 'fannym.medina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Felipe Pedraza Robayo', 'email' => 'felipe.pedraza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Felix Andrés Solano Gómez', 'email' => 'felix.solano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Fernando Alonso Diaz Medina', 'email' => 'fernando.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Francisca De Asis Ardila Guerra', 'email' => 'francisca.ardila@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Francisco Jose Petro Soto', 'email' => 'francisco.petro@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Francisco José Granados Parra', 'email' => 'francisco.granados@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Freddy Yesid Jimenez', 'email' => 'freddy.jimenez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gabriela Troncoso Nieto', 'email' => 'gabriela.troncoso@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gabriela Pérez Soto', 'email' => 'gabriela.perez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Geovanys Villanueva Torregrosa', 'email' => 'geovanys.villanueva@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gerardino Calderon Gonzalez', 'email' => 'gerardino.calderon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gina Marcela Gomez Cuellar', 'email' => 'gina.gomez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ginna Alexandra Urrego Montoya', 'email' => 'ginna.urrego@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Giuliana D\'achiardi Matta', 'email' => 'giuliana.dachiardi@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gleydis Rocio Sanchez Bedoya', 'email' => 'gleydis.sanchez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gloria Yineth Rodas Aldana', 'email' => 'gloria.rodas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Guillermo Azar Builes', 'email' => 'guillermo.azar@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Guiomar Angélica Martínez Rodríguez', 'email' => 'guiomar.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gustavo Adolfo Daza Morales', 'email' => 'gustavo.daza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gustavo Adolfo Perez Daza', 'email' => 'gustavo.perez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gustavo Adolfo Pezotti Peñaranda', 'email' => 'gustavo.pezotti@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Gustavo Javier Pacheco Vellojin', 'email' => 'gustavo.pacheco@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Heidy Yuli Sanchez Gonzalez', 'email' => 'heidy.sanchez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Henry Rodriguez Pinzon', 'email' => 'henry.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Hugo Armando Saez Soto', 'email' => 'hugo.saez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Hugo Camilo Rodriguez Riaño', 'email' => 'hugo.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Hugo Miguel Figueroa Ramos', 'email' => 'hugo.figueroa@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Hugues Rafael Quintero Jaimes', 'email' => 'hugues.quintero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Humberto Malaver Pinzon', 'email' => 'humberto.malaver@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ilba Corredor Leyva', 'email' => 'ilba.corredor@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Indira Alejandra Burbano Echeverry', 'email' => 'indira.burbano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Indira Luz Sierra Barrios', 'email' => 'indira.sierra@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ingrid Yaneth Ovalle Posada', 'email' => 'ingrid.ovalle@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Isabel Cristina Gallo Mejia', 'email' => 'isabel.gallo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Isabella Muskus Elias', 'email' => 'isabella.muskus@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ivan Francisco Fuentes Peñaloza', 'email' => 'ivan.fuentes@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ivonne Diaz Rodriguez', 'email' => 'ivonne.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jaime Gomez', 'email' => 'jaime.gomez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jaime Alfonso Lorduy de la Espriella', 'email' => 'jaime.lorduy@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jaime Andres Baleta Aponte', 'email' => 'jaime.baleta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jaime Enrique Escobar Rodriguez', 'email' => 'jaime.escobar@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jairo Eduardo Pastor Ruiz', 'email' => 'jairo.pastor@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jairo Luis Quiceno', 'email' => 'jairo.quiceno@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jamer Cortina', 'email' => 'jamer.cortina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Javier Jose Lacouture Poveda', 'email' => 'javier.lacouture@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Javith Gregorio Adechine Carrillo', 'email' => 'javith.adechine@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jeison Fajardo Meza', 'email' => 'jeison.fajardo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jeniffer Paola Henao Nivia', 'email' => 'jeniffer.henao@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jennifer Urueta Herrera', 'email' => 'jennifer.urueta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jesus Alberto Orozco Gomez', 'email' => 'jesus.orozco@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jhon Jaime Acosta Duque', 'email' => 'jhon.acosta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jhon Jairo Sanchez Navarro', 'email' => 'jhon.sanchez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jhon Kelis Atencio', 'email' => 'jhon.atencio@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jhony Alveiro Hernandez Sanabria', 'email' => 'jhony.hernandez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jhordin Stiven Suarez Lozano', 'email' => 'jhordin.suarez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jorge Otalora Aldana', 'email' => 'jorge.otalora@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jorge Andrés Villarreal Álvarez', 'email' => 'jorge.villarreal@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jorge Daniel Peralta Velásquez', 'email' => 'jorge.peralta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jose Alfonso Palma Pretelt', 'email' => 'jose.palma@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jose Amiro Molina Pumarejo', 'email' => 'jose.molina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jose Antonio Serrano Hernandez', 'email' => 'jose.serrano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Jose Ignacio Charris Salas', 'email' => 'jose.charris@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'José Teatino Avila', 'email' => 'jose.teatino@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'José Fernando Acevedo Díaz', 'email' => 'jose.acevedo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Camilo Torrez Reyes', 'email' => 'juan.torrez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Camilo Gómez', 'email' => 'juan.gomez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Carlos Padilla Sierra', 'email' => 'juan.padilla@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Carlos Ruiz García', 'email' => 'juan.ruiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Carlos Sarmiento Baquero', 'email' => 'juan.sarmiento@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan David Rodriguez Quevedo', 'email' => 'juan.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan David Lopez Martinez', 'email' => 'juan.lopez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Felipe Paz Socarras', 'email' => 'juan.paz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Felipe Del Castillo Calle', 'email' => 'juan.delcastillo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Humberto Salleg Ochoa', 'email' => 'juan.salleg@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Jose Salgado Olivares', 'email' => 'juan.salgado@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Pablo Tamara Velasquez', 'email' => 'juan.tamara@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Sebastian Ramirez Rodriguez', 'email' => 'juan.ramirez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Sebastian Galvis Martinez', 'email' => 'juan.galvis@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Juan Sebastian Aroca Mejia', 'email' => 'juan.aroca@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Julay Josefina Ramirez Campo', 'email' => 'julay.ramirez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Julia de Jesus Martinez Kerguelen', 'email' => 'julia.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Julieth Samantha Buitrago Amarillo', 'email' => 'julieth.buitrago@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Julio Hernando Cardenas Lazzo', 'email' => 'julio.cardenas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Karen Paternina', 'email' => 'karen.paternina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Karen Paola Zapata Garcia', 'email' => 'karen.zapata@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Karen Susana Diaz Guevara', 'email' => 'karen.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Karen Yiseth Daza Daza', 'email' => 'karen.daza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Karen Yuliana Castaño Castaño', 'email' => 'karen.castano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Karla Andrea Monterroza Borja', 'email' => 'karla.monterroza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Kelly del Carmen Parody Martinez', 'email' => 'kelly.parody@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Laura Alejandra Portilla lizcano', 'email' => 'laura.portilla@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Laura Daniela Calderón Pulido', 'email' => 'laura.calderon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Laura Merlieth Acuña Miranda', 'email' => 'laura.acuna@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Laura Victoria Caceres Perdomo', 'email' => 'laura.caceres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Leandra Maria Castañeda Castañeda', 'email' => 'leandra.castaneda@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Leidy Carolina Romero Martinez', 'email' => 'leidy.romero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Leivis Mariana Botina Montero', 'email' => 'mariana.botina@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lesdy Johanna Fandiño Riveros', 'email' => 'lesdy.fandino@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ligia Galeano Penagos', 'email' => 'ligia.galeano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ligia Esperanza Maranta Contreras', 'email' => 'ligia.maranta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lilia Briceño Buitrago', 'email' => 'lilia.briceno@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lilia Amparo Franco Duque', 'email' => 'lilia.franco@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Liliana Garcia Leiva', 'email' => 'liliana.garcia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Liliana Paola Ramirez Torrez', 'email' => 'liliana.ramirez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lilibeth Imperio Rojas Florez', 'email' => 'lilibeth.rojas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lilibeth Yuliet Escorcia Pardo', 'email' => 'lilibeth.escorcia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lina Marcela Castañez Leyva', 'email' => 'lina.castanez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lina Marcela Arias Guzman', 'email' => 'lina.arias@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lina María Tapia Herrera', 'email' => 'lina.tapia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Linsi Alexis Marquinez Sevillano', 'email' => 'linsi.marquinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Lissett Yubissay Mancilla Felizzola', 'email' => 'lissett.mancilla@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Loraine Stephany Toncel Medina', 'email' => 'loraine.toncel@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Loree Daza Meza', 'email' => 'loree.daza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Alberto Galeano Riorrecio', 'email' => 'luis.galeano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Alberto Segura Becerra', 'email' => 'luis.segura@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Alberto Morales Hernández', 'email' => 'luis.morales@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Alejandro Anichiarico Castillo', 'email' => 'luis.anichiarico@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Alfredo Salamanca Guillén', 'email' => 'luis.salamanca@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Eduardo Carrascal Vega', 'email' => 'luis.carrascal@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Eduardo Martinez Higuera', 'email' => 'luis.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Fernando Acuña Vega', 'email' => 'luis.acuna@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Gabriel Martinez Reza', 'email' => 'luisg.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luis Miguel Moscote Brito', 'email' => 'luis.moscote@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luisa Johanna Solano Zapata', 'email' => 'luisa.solano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luz Alejandra Maestre Rumbo', 'email' => 'luz.maestre@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luz Dari De la Cruz Herrera', 'email' => 'luz.delacruz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luz Hedy Ortiz Torres', 'email' => 'luz.ortiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luz Helena Gutierrez Suarez', 'email' => 'luz.gutierrez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Luz Maria Wills Ospina', 'email' => 'luz.wills@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Malyoris Lopez Ramos', 'email' => 'malyoris.lopez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Manuel Perez Buelvas', 'email' => 'manuel.perez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Manuel Alejandro Vence Quintero', 'email' => 'manuel.vence@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Manuel Jose Mercado Soto', 'email' => 'manuel.mercado@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Marbeluz Florez Zabaleta', 'email' => 'marbeluz.florez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Marcos Yohan Diaz Barrera', 'email' => 'marcos.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Margarita Torres Ospino', 'email' => 'margarita.torres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Margarita Rosa Sierra Acosta', 'email' => 'margarita.sierra@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Alejandra Sierra Maestre', 'email' => 'maria.sierra@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Alejandra Rangel Hernandez', 'email' => 'maria.rangel@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Andrea Mendez Marin', 'email' => 'maria.mendez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Camila Arrieta Guzman', 'email' => 'maria.arrieta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Camila Rondon Gutierrez', 'email' => 'maria.rondon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Catalina Moreno Anzola', 'email' => 'maria.moreno@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria de los Angeles Mejia Garcia', 'email' => 'maria.mejia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Ercilia Pava Vanegas', 'email' => 'maria.pava@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Fernanda Luengas Medina', 'email' => 'mariaf.luengas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Jose Pineda', 'email' => 'maria.pineda@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Jose Olivella Hernandez', 'email' => 'maria.olivella@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Jose Mejia Palencia', 'email' => 'mariajose.mejia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Judith Pinto Gómez', 'email' => 'maria.pinto@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Lucia Franco', 'email' => 'maria.franco@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Mercedes Callejas Montaña', 'email' => 'maria.callejas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Mercedes Ariza Perez', 'email' => 'maria.ariza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Nella Ortiz Martinez', 'email' => 'maria.ortiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Nubia Cifuentes', 'email' => 'maria.cifuentes@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Odeth Salazar Villarreal', 'email' => 'odeth.salazar@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Paula Diaz Laverde', 'email' => 'maria.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Paula Aruachan Elias', 'email' => 'maria.aruachan@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Paz Gutiérrez Domínguez', 'email' => 'maria.gutierrez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maria Yaneth Farfan Casallas', 'email' => 'yaneth.farfan@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Mario Fernando Zuluaga', 'email' => 'mario.zuluaga@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maritza Helena Salinas Roncancio', 'email' => 'maritza.salinas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Marling Yinaris Arregoces Lacouture', 'email' => 'marling.arregoces@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Martha Azucena Garzon', 'email' => 'martha.garzon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Martha Patricia Padilla Velasco', 'email' => 'martha.padilla@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Martin Andres Bernier Pelaez', 'email' => 'martin.bernier@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Mary Guzmán Huertas', 'email' => 'mary.guzman@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Maryin Dariany Carrascal Sanchez', 'email' => 'maryin.carrascal@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'María Catalina Valderrama Becerra', 'email' => 'maria.valderrama@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'María Nemecia Rodriguez Garcia', 'email' => 'maria.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'María Pilar Laverde', 'email' => 'maria.laverde@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Mauro Oyola Hernandez', 'email' => 'mauro.oyola@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Mayra Alejandra Duran', 'email' => 'mayra.duran@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Mayra Alejandra Urango Sierra', 'email' => 'mayra.urango@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Mery Patricia Rojas Arevalo', 'email' => 'patricia.rojas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Miguel Angel Durango Soto', 'email' => 'miguel.durango@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Milagro del Carmen Gamarra Rueda', 'email' => 'milagro.gamarra@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Miry Alejandra Tuiran carrascal', 'email' => 'miry.tuiran@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Monica Rodriguez Martinez', 'email' => 'monica.rodriguez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Monica Alexandra Manrique Narvaez', 'email' => 'monica.manrique@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Monica Maria Florez Ramirez', 'email' => 'monica.florez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nacira Esther Prieto Gonzalez', 'email' => 'nacira.prieto@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nancy Montero Betancur', 'email' => 'nancy.montero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nancy Stella Muñoz Arias', 'email' => 'nancy.munoz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Natalia Catalina Benitez Yepez', 'email' => 'natalia.benitez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nelly Rincon Leon', 'email' => 'nelly.rincon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nelson Miguel Amaya Pinto', 'email' => 'nelson.amaya@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nelson Ricardo Carreño Barrera', 'email' => 'nelson.carreno@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nestor Danith Del Toro Martinez', 'email' => 'nestor.deltoro@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nicolas Ortega Morat', 'email' => 'nicolas.ortega@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nisson Alfredo Vahos perez', 'email' => 'nisson.vahos@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Nohora Clemencia Sanabria Aguilar', 'email' => 'nohora.sanabria@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Olga Lucia Cardona Sanchez', 'email' => 'olga.cardona@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Omar Forero Porras', 'email' => 'omar.forero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Omar Yessid Toncel Churio', 'email' => 'omar.toncel@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Oriana Paola Gonzalez Martinez', 'email' => 'oriana.gonzalez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Oriana Silena Romero Torres', 'email' => 'oriana.romero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Oscar Gutiérrez Tique', 'email' => 'oscar.gutierrez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Oscar Olimpo Oliver Vivero', 'email' => 'oscar.oliver@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Osmar Enrique Godoy Gutiérrez', 'email' => 'osmar.godoy@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Pamela Carolina Pinto Rosado', 'email' => 'pamela.pinto@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paola Alexandra Polo Orozco', 'email' => 'paola.polo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paola Andrea Tamayo Habib', 'email' => 'paola.tamayo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paola Andrea Mariño Puentes', 'email' => 'paola.marino@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paola Andrea Gaitan Guerra', 'email' => 'paola.gaitan@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paola Andrea León Corredor', 'email' => 'paola.leon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Patricia Isabel Diaz Pastrana', 'email' => 'patricia.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paul Villero Alvis', 'email' => 'paul.villero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Paula Andrea Jimenez Rios', 'email' => 'paula.jimenez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Pedro Benjamin Arrieta Petro', 'email' => 'pedro.arrieta@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rafael Eduardo Cammerer Cuadrado', 'email' => 'rafael.cammerer@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rafael Jose Garcia Espinosa', 'email' => 'rafael.garcia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Raimundo Guillermo Cohen Cogollo', 'email' => 'raimundo.cohen@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ramiro Alberto Morales Diaz', 'email' => 'ramiro.morales@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Raúl Andrés Santana Hernández', 'email' => 'raul.santana@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ricardo Andres Toledo Pinto', 'email' => 'ricardo.toledo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ricardo David Castellanos', 'email' => 'ricardo.castellanos@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Richard Javier Garzon Uzeta', 'email' => 'richard.garzon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rinna Yohana Martinez', 'email' => 'rinna.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rita Omaira Martinez Avellaneda', 'email' => 'roma@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Roberth Jose Angulo', 'email' => 'roberth.angulo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Roberto Velez Cabrales', 'email' => 'roberto.velez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Robinson Quintero Duque', 'email' => 'robinson.quintero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rodrigo Alberto Hernandez Sarabia', 'email' => 'rodrigo.hernandez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rodrigo Alfonso Ariza Ortiz', 'email' => 'rodrigoa.ariza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rosaury Daniela Yejas Rivera', 'email' => 'rosaury.yejas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rossana Guerrero Percy', 'email' => 'rossana.guerrero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ruben Dario Petro Lemus', 'email' => 'ruben.petro@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Rubiela Quiceno Echeverry', 'email' => 'rubiela.quinceno@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sallys Milena Atencio Molina', 'email' => 'sallys.atencio@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Samuel Alejandro Trujillo Castañeda', 'email' => 'samuel.trujillo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Samuel Camilo Villero Giraldo', 'email' => 'samuel.villero@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sandra Custodia Jiménez Vásquez', 'email' => 'sandra.jimenez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sandra Milena Benavides Martinez', 'email' => 'sandra.benavides@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sandra Milena Farfan Briceño', 'email' => 'sandra.farfan@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sandra Patricia Moreno Ortega', 'email' => 'sandra.moreno@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Saul Hernando Gomez Castillo', 'email' => 'saul.gomez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sebastian Ruiz Perez', 'email' => 'sebastian.ruiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sebastian Torres Sánchez', 'email' => 'sebastian.torres@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sergio Calderón Hernández', 'email' => 'sergio.calderon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sergio Daniel Martinez', 'email' => 'sergio.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sharon Nisperuza', 'email' => 'sharon.nisperuza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Silvano Martinez Lopez', 'email' => 'silvano.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Silvestre de Jesus Saurith Polo', 'email' => 'silvestre.saurith@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Silvio Rivera Dominguez', 'email' => 'silvio.rivera@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sirly Dayari Triana Contreras', 'email' => 'sirly.triana@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sofia Besaile Elias', 'email' => 'sofia.besaile@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sol Marina Cure Florez', 'email' => 'sol.cure@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sonia Saucedo Mendoza', 'email' => 'sonia.saucedo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sonia Patricia Cruz Ortega', 'email' => 'sonia.cruz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sonya Yamile Soche Solorzano', 'email' => 'sonya.soche@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Sthefanie Puentes León', 'email' => 'sthefanie.puentes@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Tatiana Perez Sierra', 'email' => 'tatiana.perezs@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Tatiana Maria Pelaez Pereira', 'email' => 'tatiana.pelaez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Valentina Hernandez Diaz', 'email' => 'valentina.hernandez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Vilma Ruiz', 'email' => 'vilma.ruiz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Vivian Aminta Gaviria Tapias', 'email' => 'vivian.gaviria@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'William Fernando Olivares Lopez', 'email' => 'william.olivares@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'William Roberto Pinzon Amezquita', 'email' => 'william.pinzon@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Wilson Cepeda Rubiano', 'email' => 'wilson.cepeda@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Wilson Elles Maestre', 'email' => 'wilson.elles@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Wilson Javier Cabadia Bolaño', 'email' => 'wilson.cabadia@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Xavier Augusto Noriega Sirtori', 'email' => 'xavier.noriega@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Ximena Diaz Romero', 'email' => 'ximena.diaz@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Xiomara Rojas Rivera', 'email' => 'xiomara.rojas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yeferson Bolaño Garcia', 'email' => 'yeferson.bolano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yeinson Eliecer Castaño León', 'email' => 'yeinson.castano@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yeli Andrea Acuña Gutierrez', 'email' => 'yeli.acuna@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yenifer Charry Ramirez', 'email' => 'yenifer.charry@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yolima Villanueva Jimenez', 'email' => 'yolima.villanueva@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yonny Estiven Barón', 'email' => 'yonny.baron@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yorgelis María Salas Ospino', 'email' => 'yorgelis.salas@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yubisay Martínez', 'email' => 'yubisay.martinez@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yujeiri Pedraza', 'email' => 'yujeiri.pedraza@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yuli Paola Perdomo Navarro', 'email' => 'paola.perdomo@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Yuri Andrea Osorio Marquez', 'email' => 'yuri.osorio@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
            ['name' => 'Zayda Catalina Pastrana Martinez', 'email' => 'zayda.pastrana@fps.gov.co', 'password' => Hash::make('Ferrocarriles2024*'), 'rol_id' => 2],
        ];

        DB::table('users')->insert($users);
    }
}
